import os
import json
import subprocess
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOOK_DIR = os.path.join(BASE_DIR, "output", "book")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
OUTLINE_PATH = os.path.join(OUTPUT_DIR, "book_outline.json")


def combine_chapters():
    with open(OUTLINE_PATH, "r", encoding="utf-8") as f:
        outline = json.load(f)

    book_title = outline.get("book_title", "LLM Book")
    author = "Generated by LLM Pipeline"
    date = datetime.now().strftime("%B %Y")

    chapters = outline["chapters"]

    print(f" Combining {len(chapters)} chapters...")


    full_md = f"""
% {book_title}
% {author}
% {date}

\\newpage
"""


    full_md += "## Table of Contents\n\n"
    for ch in chapters:
        full_md += f"{ch['chapter_number']}. {ch['chapter_title']}\n"
    full_md += "\n\\newpage\n"


    for ch in chapters:
        num = ch["chapter_number"]
        filename = f"chapter_{str(num).zfill(2)}.md"
        path = os.path.join(BOOK_DIR, filename)

        if not os.path.exists(path):
            print(f" Missing: {filename}")
            continue

        with open(path, "r", encoding="utf-8") as f:
            content = f.read()

        
        full_md += f"\n\\newpage\n\n"
        full_md += content
        full_md += "\n\n"

    md_path = os.path.join(OUTPUT_DIR, "full_book.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(full_md)

    print(f" Combined markdown → output/full_book.md")
    return md_path, book_title



def build_pdf(md_path, book_title):
    pdf_path = os.path.join(OUTPUT_DIR, "book.pdf")

    print(" Building PDF with Pandoc...")

    cmd = [
        "pandoc", md_path,
        "-o", pdf_path,
        "--pdf-engine=xelatex",
        "--toc",
        "--toc-depth=2",
        "-V", "geometry:margin=1in",
        "-V", "mainfont=Times New Roman",
        "-V", "fontsize=12pt",
        "-V", f"title={book_title}",
        "-V", "author=LLM Book Pipeline",
        "-V", "colorlinks=true",
        "-V", "linkcolor=blue",
        "--highlight-style=espresso"
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode == 0:
        size_kb = os.path.getsize(pdf_path) // 1024
        print(f" PDF created → output/book.pdf ({size_kb}KB)")
    else:
        print(" Pandoc failed:")
        print(result.stderr[:300])



if __name__ == "__main__":
    md_path, book_title = combine_chapters()
    build_pdf(md_path, book_title)

    print("\n STEP 6 COMPLETE!")
    print(" Files generated:")
    print("   output/full_book.md")
    print("   output/book.pdf")